name: Todo Frontend

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install Dependencies
        run: yarn install
        working-directory: todo-frontend
      - run: yarn lint
        working-directory: todo-frontend
      - run: yarn type-check
        working-directory: todo-frontend

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install Dependencies
        run: yarn install
        working-directory: todo-frontend
      - run: yarn test --ci --collect-coverage --verbose
        working-directory: todo-frontend
