name: Todo Infra

on: [push, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Checkov
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infra/
          framework: terraform
  
  database-migrations:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update &&
          sudo apt-get install --yes postgresql-client
      - name: Run database migrations
        run: for i in db-init; do echo "Executing script $i..."; bash db-init/$i; done
        working-directory: todo-backend
        env:
          POSTGRES_ADDRESS: ${{ secrets.POSTGRES_ADDRESS }}
          POSTGRES_USER: ${{ secrets.POSTGRES_ADMIN_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_ADMIN_PASSWORD }}
          POSTGRES_APP_PASSWORD: ${{ secrets.POSTGRES_APP_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DATABASE }}
